#define SERVO_CLAW_LOW_PULSE_WIDTH 970
#define SERVO_CLAW_HIGH_PULSE_WIDTH 1955
#define SERVO_Z_LOW_PULSE_WIDTH 980
#define SERVO_Z_HIGH_PULSE_WIDTH 1965
#define SERVO_ROT_LOW_PULSE_WIDTH 970
#define SERVO_ROT_HIGH_PULSE_WIDTH 1955

